[book]
title = "넷평의 Clojure 노트"
description = "study.clojure    "
authors = ["netpyoung"]
language = "kr"
multilingual = false
src = "src"

[output.html]
no-section-label = true
site-url = "/study.clojure/"
git-repository-url = "https://github.com/netpyoung/study.clojure"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/netpyoung/study.clojure/edit/main/{path}"